#!/usr/bin/env python3
"""
AI Email Assistant - Create and manage company emails
"""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Company email config
SENDER = "everycompanyclaw@gmail.com"
APP_PASSWORD = os.environ.get("GMAIL_APP_PASSWORD", "ifwubwz pkqtievqh")

# AI-generated email templates
EMAIL_TEMPLATES = {
    "welcome": """Subject: Welcome to EveryCompanyClaw! 🧵

Hi {name},

Thank you for your interest in our automation services!

We help businesses save 10+ hours/week through:
- Python automation scripts
- Workflow templates
- AI integration

Your free consultation: https://everycompanyclaw.github.io/company-automation/

Best regards,
MK
EveryCompanyClaw""",

    "order_confirm": """Subject: Order Confirmed - {product}

Hi {name},

Thank you for your purchase!

Product: {product}
Price: ${price}

Download: {download_link}

Questions? Reply to this email!

Best,
EveryCompanyClaw""",

    "followup": """Subject: Following up - Automation for {company}

Hi {name},

Just checking in on my last email about automation.

Questions?
- What tasks take most of your time?
- What would you automate if you could?

Happy to help!

Best,
MK
EveryCompanyClaw""",

    "invoice": """Subject: Invoice #{invoice_num} - EveryCompanyClaw

Hi {name},

Please find invoice details below:

Service: {service}
Amount: ${amount}
Due: {due_date}

Payment link: {payment_link}

Best,
EveryCompanyClaw"""
}

def generate_email(template_name, **kwargs):
    """Generate email from template with AI-style personalization"""
    template = EMAIL_TEMPLATES.get(template_name, EMAIL_TEMPLATES["welcome"])
    
    # Add AI-style touches
    kwargs["ai_note"] = "🤖 Generated by EveryCompanyClaw AI"
    
    try:
        email = template.format(**kwargs)
        return email
    except KeyError as e:
        return f"Error: Missing template variable: {e}"

def send_email(to_email, subject, body):
    """Send email"""
    msg = MIMEMultipart()
    msg['From'] = SENDER
    msg['To'] = to_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))
    
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(SENDER, APP_PASSWORD)
        server.sendmail(SENDER, to_email, msg.as_string())
        server.quit()
        return True
    except Exception as e:
        print(f"Error: {e}")
        return False

def ai_respond(inquiry_type, customer_name, details=""):
    """AI-style response to common inquiries"""
    
    responses = {
        "pricing": f"""Hi {customer_name},

Thank you for your interest!

Our services:
- Python Scripts Bundle: $79
- Zapier Templates: $49  
- AI Prompts Library: $29
- Custom Automation: $500-4000

Get started: https://everycompanyclaw.github.io/company-automation/

Best,
EveryCompanyClaw 🧵""",

        "demo": f"""Hi {customer_name},

I'd love to show you what we do!

Quick demo options:
- 15 min call
- Screen share walkthrough
- Written case studies

Reply with what works for you!

Best,
MK""",

        "support": f"""Hi {customer_name},

Thanks for reaching out!

{details}

We'll get back to you within 24 hours.

Best,
EveryCompanyClaw""",
    }
    
    return responses.get(inquiry_type, responses["support"])

# Usage examples
if __name__ == "__main__":
    print("📧 AI Email Assistant")
    print("=" * 40)
    print("\nAvailable templates:")
    for k in EMAIL_TEMPLATES.keys():
        print(f"  - {k}")
    
    print("\nExample - Welcome email:")
    print(generate_email("welcome", name="John"))
    
    print("\nExample - AI response to pricing inquiry:")
    print(ai_respond("pricing", "John"))
