#!/usr/bin/env python3
"""
Project Publisher - Creates and publishes new projects every 3 days
Based on lead research and target audience
"""
import os
import json
import requests
from datetime import datetime, timedelta

PROJECTS_DIR = "/Users/macbookpro/.openclaw/workspace/company/projects"
LEADS_FILE = "/tmp/leads.json"
LOG_FILE = "/tmp/project_publisher.log"

# Target audiences we serve
AUDIENCES = [
    {"name": "Startups", "pain": "need automation", "solution": "AI agents"},
    {"name": "Small Business", "pain": "limited time", "solution": "Workflow automation"},
    {"name": "Developers", "pain": "repetitive tasks", "solution": "Code automation"},
    {"name": "Marketers", "pain": "content creation", "solution": "AI content tools"},
    {"name": "E-commerce", "pain": "customer support", "solution": " chatbots"},
]

# Project templates based on research
def generate_project(lead, audience):
    """Generate a project based on lead research + target audience"""
    
    company = lead.get("company", "Unknown")
    source = lead.get("source", "unknown")
    
    project = f"""# 🎯 {company} - {audience['name']} Solution

## Research Summary
- **Source**: {lead.get('name', 'Unknown')}
- **Company**: {company}
- **Original Source**: {source}
- **Research Date**: {datetime.now().strftime("%Y-%m-%d")}

## Target Audience
- **Who**: {audience['name']}
- **Pain Point**: {audience['pain']}
- **Our Solution**: {audience['solution']}

## Problem Statement
{audience['name']} struggle with {audience['pain']}. 
{company}'s technology can help solve this.

## Solution Overview
We propose an integration between our automation platform and {company}'s API.

### Key Features
1. Automated workflow for {audience['name']}
2. {audience['solution']} integration
3. Real-time data sync
4. 24/7 monitoring

## Technical Implementation
- **API**: RESTful integration with {company}
- **Stack**: Python, OpenClaw, GitHub Actions
- **Deployment**: GitHub Pages + Vercel

## Business Model
- **Pricing**: $79/month per user
- **Target**: 100 {audience['name']} in Q2
- **Revenue Potential**: $7,900/month

## Next Steps
- [ ] Contact {company} for partnership
- [ ] Build MVP integration
- [ ] Launch to {audience['name']} audience
- [ ] Gather feedback and iterate

---
*Generated by EveryCompanyClaw AI Agent - {datetime.now().strftime("%Y-%m-%d %H:%M")}*
"""
    return project

def get_latest_project_date():
    """Get the date of the latest published project"""
    if not os.path.exists(PROJECTS_DIR):
        return None
    
    files = [f for f in os.listdir(PROJECTS_DIR) if f.endswith(".md")]
    if not files:
        return None
    
    # Get most recently modified file
    files_with_time = [(f, os.path.getmtime(os.path.join(PROJECTS_DIR, f))) for f in files]
    files_with_time.sort(key=lambda x: x[1], reverse=True)
    
    latest_file = files_with_time[0][0]
    latest_time = datetime.fromtimestamp(files_with_time[0][1])
    return latest_time

def should_publish():
    """Check if we should publish a new project (every 3 days)"""
    last_published = get_latest_project_date()
    
    if last_published is None:
        return True
    
    days_since = (datetime.now() - last_published).days
    return days_since >= 3

def publish_project():
    """Main function to publish a new project"""
    # Load leads
    try:
        with open(LEADS_FILE) as f:
            leads_data = json.load(f)
            leads = leads_data.get("leads", [])
    except:
        print("No leads file found")
        return False
    
    if not leads:
        print("No leads available")
        return False
    
    # Get a lead we haven't used recently
    # Use lead based on day of year to cycle through
    day_of_year = datetime.now().timetuple().tm_yday
    lead_index = day_of_year % len(leads)
    lead = leads[lead_index]
    
    # Get audience based on another cycle
    audience_index = (day_of_year // 3) % len(AUDIENCES)
    audience = AUDIENCES[audience_index]
    
    # Generate project
    company = lead.get("company", "project")[:30].replace(" ", "-")
    project = generate_project(lead, audience)
    
    # Save project
    os.makedirs(PROJECTS_DIR, exist_ok=True)
    filename = f"{company}-for-{audience['name'].lower()}.md"
    filepath = os.path.join(PROJECTS_DIR, filename)
    
    with open(filepath, "w") as f:
        f.write(project)
    
    print(f"✅ Published: {filename}")
    print(f"   Lead: {lead.get('company')}")
    print(f"   Audience: {audience['name']}")
    
    return True

def main():
    print("📦 Project Publisher")
    print("=" * 40)
    
    if should_publish():
        print("Time to publish a new project!")
        publish_project()
    else:
        last = get_latest_project_date()
        days = (datetime.now() - last).days if last else 0
        print(f"Last project: {days} days ago")
        print("Next publish in {3 - days} days")

if __name__ == "__main__":
    main()